name: openci_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_ui_auth: ^1.12.0
  hooks_riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  cloud_firestore: ^4.15.9
  signals_flutter: ^4.5.1
  http: ^1.2.1
  awesome_extensions: ^2.0.13
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true
